seeds:
  - name: raw_to_stg_config
    config:
      column_types:
        raw_table_name: STRING
        raw_column_name: STRING
        target_column_name: STRING
        target_data_type: STRING
        target_order_num: INT
        notes: STRING
